// Real Binance completed-trade accounting: the arithmetic, with no imports.
//
// This is the customer's ACTUAL money. It is deliberately kept apart from
// lib/engine.ts, which computes the STRATEGY's modelled result by multiplying a
// fractional return by the `capital_usd` config column. The two must never be
// summed, averaged, or shown under one label — a modelled +$120 and a realised
// +$11.66 are different kinds of fact, and merging them is how a client comes
// to believe a paper result was a real one.
//
// Nothing here reads a fee percentage, a fee rate, or `capital_usd`. Every
// figure below comes from `executed_trades`, whose rows are written only from
// Binance's own fill and income records.
//
// Import-free on purpose, so it can be tested with `node --test` and no
// Supabase client:
//
//   node --test src/lib/accounting.test.ts

/** One completed Binance trade, exactly as `executed_trades` stores it. */
export interface ExecutedTradeRow {
  id: string;
  user_id: string;
  symbol: string;
  side: "LONG" | "SHORT" | string;
  open_binance_order_id: string;
  close_binance_order_id: string;
  entry_time: string;
  exit_time: string;
  qty: number | null;
  entry_avg_price: number | null;
  exit_avg_price: number | null;
  /** How many Binance fills were aggregated into entry_avg_price. */
  entry_fill_count: number;
  /** How many Binance fills were aggregated into exit_avg_price. */
  exit_fill_count: number;
  /** More than one when the position was closed in stages. */
  exit_order_count: number;
  /**
   * How the position left the account. Helix opened every trade recorded here;
   * this says who closed it — the bot, the client by hand in the Binance app or
   * an exchange-side stop, or both in stages. All three are fully accounted.
   */
  close_source: "HELIX" | "EXTERNAL" | "MIXED" | string;
  /** Binance realizedPnl, before commission and before funding. */
  gross_pnl_usd: number | null;
  entry_commission_usd: number | null;
  exit_commission_usd: number | null;
  /** Generated by the database: entry + exit commission. Always a cost. */
  commission_usd: number | null;
  /** Binance sign convention: negative means the customer paid funding. */
  funding_usd: number | null;
  funding_event_count: number;
  /** Generated by the database: gross - commission + funding. */
  net_pnl_usd: number | null;
  accounting_status: "COMPLETE" | "INCOMPLETE" | string;
  incomplete_reason: string | null;
  source: string;
  synced_at: string;
}

/**
 * True only when Binance gave us every number this trade needs.
 *
 * An INCOMPLETE row is still shown to the customer — the trade happened — but
 * its money columns are null and must render as "unavailable", never as 0.
 */
export function isComplete(t: ExecutedTradeRow): boolean {
  return (
    t.accounting_status === "COMPLETE" &&
    t.net_pnl_usd !== null &&
    t.gross_pnl_usd !== null &&
    t.commission_usd !== null &&
    t.funding_usd !== null
  );
}

export interface RealPerformance {
  /** Trades whose accounting is fully established. */
  trades: number;
  /** Trades Binance executed that we could not price exactly. */
  incompleteTrades: number;
  grossPnl: number;
  /** Always >= 0. Displayed as a deduction. */
  commission: number;
  /** Binance sign: negative = paid. */
  funding: number;
  netPnl: number;
  wins: number;
  losses: number;
  /** Percentage. Measured on NET, after commission. */
  winRate: number;
}

export const EMPTY_REAL_PERFORMANCE: RealPerformance = {
  trades: 0,
  incompleteTrades: 0,
  grossPnl: 0,
  commission: 0,
  funding: 0,
  netPnl: 0,
  wins: 0,
  losses: 0,
  winRate: 0,
};

/**
 * Totals across real Binance trades.
 *
 * Incomplete rows contribute to `incompleteTrades` and to nothing else: a trade
 * we cannot price must not drag a total toward zero as though it broke even.
 *
 * A win is a trade the CUSTOMER made money on — net, after commission. A trade
 * that grossed +$0.50 and cost $0.84 in fees is a loss, and reporting it as a
 * win would be reporting the strategy's result as the customer's.
 */
export function realPerformance(rows: readonly ExecutedTradeRow[]): RealPerformance {
  const out: RealPerformance = { ...EMPTY_REAL_PERFORMANCE };
  for (const t of rows) {
    if (!isComplete(t)) {
      out.incompleteTrades += 1;
      continue;
    }
    out.trades += 1;
    out.grossPnl += Number(t.gross_pnl_usd);
    out.commission += Number(t.commission_usd);
    out.funding += Number(t.funding_usd);
    out.netPnl += Number(t.net_pnl_usd);
    if (Number(t.net_pnl_usd) > 0) out.wins += 1;
    else if (Number(t.net_pnl_usd) < 0) out.losses += 1;
  }
  out.winRate = out.trades ? (out.wins / out.trades) * 100 : 0;
  return out;
}

/** Real trades that closed on a given local day. */
export function closedOn(rows: readonly ExecutedTradeRow[], day: Date): ExecutedTradeRow[] {
  const key = day.toDateString();
  return rows.filter((t) => t.exit_time && new Date(t.exit_time).toDateString() === key);
}

/** The dashboard's "today" figures, over real Binance trades only. */
export function realTotalsForDay(
  rows: readonly ExecutedTradeRow[],
  day: Date = new Date(),
): RealPerformance {
  return realPerformance(closedOn(rows, day));
}

// ----- Export -----

/**
 * CSV of real Binance accounting.
 *
 * Separate from the strategy export, and every column name says which fact it
 * carries. An INCOMPLETE trade exports empty money cells plus its reason, so a
 * spreadsheet cannot silently read "we do not know" as zero.
 */
export const REAL_TRADE_CSV_HEADER = [
  "symbol",
  "side",
  "entry_time",
  "exit_time",
  "qty",
  "entry_avg_price",
  "exit_avg_price",
  "entry_fill_count",
  "exit_fill_count",
  "exit_order_count",
  "gross_pnl_usd",
  "entry_commission_usd",
  "exit_commission_usd",
  "commission_usd",
  "funding_usd",
  "net_pnl_usd",
  "open_binance_order_id",
  "close_binance_order_id",
  "close_source",
  "accounting_status",
  "incomplete_reason",
].join(",");

function cell(v: number | string | null | undefined): string {
  if (v === null || v === undefined) return "";
  const s = String(v);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function realTradesCsv(rows: readonly ExecutedTradeRow[]): string {
  return [
    REAL_TRADE_CSV_HEADER,
    ...rows.map((t) =>
      [
        cell(t.symbol),
        cell(t.side),
        cell(t.entry_time),
        cell(t.exit_time),
        cell(t.qty),
        cell(t.entry_avg_price),
        cell(t.exit_avg_price),
        cell(t.entry_fill_count),
        cell(t.exit_fill_count),
        cell(t.exit_order_count),
        cell(t.gross_pnl_usd),
        cell(t.entry_commission_usd),
        cell(t.exit_commission_usd),
        cell(t.commission_usd),
        cell(t.funding_usd),
        cell(t.net_pnl_usd),
        cell(t.open_binance_order_id),
        cell(t.close_binance_order_id),
        cell(t.close_source),
        cell(t.accounting_status),
        cell(t.incomplete_reason),
      ].join(","),
    ),
  ].join("\n");
}

// ----- Display helpers -----

/** What a customer should read when a figure is not established. */
export const UNAVAILABLE = "unavailable";

/**
 * Commission always reads as money leaving the account.
 *
 * `commission_usd` is stored as a positive cost, so the minus sign is added
 * here rather than by negating the stored value — the deduction is a property
 * of the display, and the stored number stays the amount Binance charged.
 */
export function fmtCommission(commission: number | null | undefined): string {
  if (commission === null || commission === undefined) return UNAVAILABLE;
  if (commission === 0) return "$0.00";
  return `−$${Math.abs(commission).toLocaleString(undefined, {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

/** Success for a real net gain, destructive for a real net loss. */
export function netTone(net: number | null | undefined): "success" | "destructive" | "muted" {
  if (net === null || net === undefined) return "muted";
  return net >= 0 ? "success" : "destructive";
}

/**
 * Plain-language rendering of close_source.
 *
 * A client who closed a bot position themselves — or whose position was taken
 * out by an exchange-side stop — must be able to see that in their history.
 * The trade is accounted for exactly the same way, because the fills are the
 * truth regardless of who sent the closing order.
 */
export function closeSourceLabel(source: string): string | null {
  if (source === "EXTERNAL") return "Closed outside Helix";
  if (source === "MIXED") return "Partly closed outside Helix";
  return null;
}

/** Plain-language rendering of an incomplete_reason code, for the customer. */
export function incompleteLabel(reason: string | null): string {
  if (!reason) return "Accounting incomplete";
  if (reason.startsWith("non_usdt_commission_asset")) {
    const asset = reason.split(":")[1] ?? "another asset";
    return `Commission charged in ${asset}, not USDT — not converted`;
  }
  if (reason.startsWith("non_usdt_funding_asset")) {
    const asset = reason.split(":")[1] ?? "another asset";
    return `Funding settled in ${asset}, not USDT — not converted`;
  }
  const known: Record<string, string> = {
    missing_entry_fills: "Binance fills for the entry order not available",
    missing_exit_fills: "Binance fills for the exit order not available",
    entry_exit_quantity_mismatch: "Entry and exit quantities do not match",
    unexpected_fill_direction: "Fill direction does not match the order",
    opening_order_realized_pnl: "Entry order was not opened from a flat position",
    zero_fill_quantity: "Fill quantity was zero",
    negative_aggregate_commission: "Binance reported a negative total commission",
    multiple_opening_orders: "The position was built by more than one order",
    external_order_added_to_position: "An order Helix did not send added to this position",
  };
  return known[reason] ?? "Accounting incomplete";
}
