/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppEngineRouteImport } from './routes/app.engine'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppConnectRouteImport } from './routes/app.connect'
import { Route as AppConfigureRouteImport } from './routes/app.configure'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as ApiPublicEngineHeartbeatRouteImport } from './routes/api/public/engine/heartbeat'
import { Route as ApiPublicEngineEthPriceRouteImport } from './routes/api/public/engine/eth-price'
import { Route as ApiPublicEngineDemoTickRouteImport } from './routes/api/public/engine/demo-tick'
import { Route as ApiPublicEngineConfigRouteImport } from './routes/api/public/engine/config'
import { Route as ApiPublicEngineSignalsPendingRouteImport } from './routes/api/public/engine/signals.pending'
import { Route as ApiPublicEngineIngestTradeRouteImport } from './routes/api/public/engine/ingest.trade'
import { Route as ApiPublicEngineIngestSignalRouteImport } from './routes/api/public/engine/ingest.signal'
import { Route as ApiPublicEngineIngestOrderRouteImport } from './routes/api/public/engine/ingest.order'
import { Route as ApiPublicEngineIngestOpen_positionsRouteImport } from './routes/api/public/engine/ingest.open_positions'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppEngineRoute = AppEngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppConfigureRoute = AppConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicEngineHeartbeatRoute =
  ApiPublicEngineHeartbeatRouteImport.update({
    id: '/api/public/engine/heartbeat',
    path: '/api/public/engine/heartbeat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEngineEthPriceRoute = ApiPublicEngineEthPriceRouteImport.update({
  id: '/api/public/engine/eth-price',
  path: '/api/public/engine/eth-price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEngineDemoTickRoute = ApiPublicEngineDemoTickRouteImport.update({
  id: '/api/public/engine/demo-tick',
  path: '/api/public/engine/demo-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEngineConfigRoute = ApiPublicEngineConfigRouteImport.update({
  id: '/api/public/engine/config',
  path: '/api/public/engine/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEngineSignalsPendingRoute =
  ApiPublicEngineSignalsPendingRouteImport.update({
    id: '/api/public/engine/signals/pending',
    path: '/api/public/engine/signals/pending',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEngineIngestTradeRoute =
  ApiPublicEngineIngestTradeRouteImport.update({
    id: '/api/public/engine/ingest/trade',
    path: '/api/public/engine/ingest/trade',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEngineIngestSignalRoute =
  ApiPublicEngineIngestSignalRouteImport.update({
    id: '/api/public/engine/ingest/signal',
    path: '/api/public/engine/ingest/signal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEngineIngestOrderRoute =
  ApiPublicEngineIngestOrderRouteImport.update({
    id: '/api/public/engine/ingest/order',
    path: '/api/public/engine/ingest/order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEngineIngestOpen_positionsRoute =
  ApiPublicEngineIngestOpen_positionsRouteImport.update({
    id: '/api/public/engine/ingest/open_positions',
    path: '/api/public/engine/ingest/open_positions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/configure': typeof AppConfigureRoute
  '/app/connect': typeof AppConnectRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/engine': typeof AppEngineRoute
  '/app/history': typeof AppHistoryRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/engine/config': typeof ApiPublicEngineConfigRoute
  '/api/public/engine/demo-tick': typeof ApiPublicEngineDemoTickRoute
  '/api/public/engine/eth-price': typeof ApiPublicEngineEthPriceRoute
  '/api/public/engine/heartbeat': typeof ApiPublicEngineHeartbeatRoute
  '/api/public/engine/ingest/open_positions': typeof ApiPublicEngineIngestOpen_positionsRoute
  '/api/public/engine/ingest/order': typeof ApiPublicEngineIngestOrderRoute
  '/api/public/engine/ingest/signal': typeof ApiPublicEngineIngestSignalRoute
  '/api/public/engine/ingest/trade': typeof ApiPublicEngineIngestTradeRoute
  '/api/public/engine/signals/pending': typeof ApiPublicEngineSignalsPendingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/configure': typeof AppConfigureRoute
  '/app/connect': typeof AppConnectRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/engine': typeof AppEngineRoute
  '/app/history': typeof AppHistoryRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/public/engine/config': typeof ApiPublicEngineConfigRoute
  '/api/public/engine/demo-tick': typeof ApiPublicEngineDemoTickRoute
  '/api/public/engine/eth-price': typeof ApiPublicEngineEthPriceRoute
  '/api/public/engine/heartbeat': typeof ApiPublicEngineHeartbeatRoute
  '/api/public/engine/ingest/open_positions': typeof ApiPublicEngineIngestOpen_positionsRoute
  '/api/public/engine/ingest/order': typeof ApiPublicEngineIngestOrderRoute
  '/api/public/engine/ingest/signal': typeof ApiPublicEngineIngestSignalRoute
  '/api/public/engine/ingest/trade': typeof ApiPublicEngineIngestTradeRoute
  '/api/public/engine/signals/pending': typeof ApiPublicEngineSignalsPendingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/configure': typeof AppConfigureRoute
  '/app/connect': typeof AppConnectRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/engine': typeof AppEngineRoute
  '/app/history': typeof AppHistoryRoute
  '/app/reports': typeof AppReportsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/public/engine/config': typeof ApiPublicEngineConfigRoute
  '/api/public/engine/demo-tick': typeof ApiPublicEngineDemoTickRoute
  '/api/public/engine/eth-price': typeof ApiPublicEngineEthPriceRoute
  '/api/public/engine/heartbeat': typeof ApiPublicEngineHeartbeatRoute
  '/api/public/engine/ingest/open_positions': typeof ApiPublicEngineIngestOpen_positionsRoute
  '/api/public/engine/ingest/order': typeof ApiPublicEngineIngestOrderRoute
  '/api/public/engine/ingest/signal': typeof ApiPublicEngineIngestSignalRoute
  '/api/public/engine/ingest/trade': typeof ApiPublicEngineIngestTradeRoute
  '/api/public/engine/signals/pending': typeof ApiPublicEngineSignalsPendingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/configure'
    | '/app/connect'
    | '/app/dashboard'
    | '/app/engine'
    | '/app/history'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/api/public/engine/config'
    | '/api/public/engine/demo-tick'
    | '/api/public/engine/eth-price'
    | '/api/public/engine/heartbeat'
    | '/api/public/engine/ingest/open_positions'
    | '/api/public/engine/ingest/order'
    | '/api/public/engine/ingest/signal'
    | '/api/public/engine/ingest/trade'
    | '/api/public/engine/signals/pending'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/admin'
    | '/app/configure'
    | '/app/connect'
    | '/app/dashboard'
    | '/app/engine'
    | '/app/history'
    | '/app/reports'
    | '/app/settings'
    | '/app'
    | '/api/public/engine/config'
    | '/api/public/engine/demo-tick'
    | '/api/public/engine/eth-price'
    | '/api/public/engine/heartbeat'
    | '/api/public/engine/ingest/open_positions'
    | '/api/public/engine/ingest/order'
    | '/api/public/engine/ingest/signal'
    | '/api/public/engine/ingest/trade'
    | '/api/public/engine/signals/pending'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/configure'
    | '/app/connect'
    | '/app/dashboard'
    | '/app/engine'
    | '/app/history'
    | '/app/reports'
    | '/app/settings'
    | '/app/'
    | '/api/public/engine/config'
    | '/api/public/engine/demo-tick'
    | '/api/public/engine/eth-price'
    | '/api/public/engine/heartbeat'
    | '/api/public/engine/ingest/open_positions'
    | '/api/public/engine/ingest/order'
    | '/api/public/engine/ingest/signal'
    | '/api/public/engine/ingest/trade'
    | '/api/public/engine/signals/pending'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicEngineConfigRoute: typeof ApiPublicEngineConfigRoute
  ApiPublicEngineDemoTickRoute: typeof ApiPublicEngineDemoTickRoute
  ApiPublicEngineEthPriceRoute: typeof ApiPublicEngineEthPriceRoute
  ApiPublicEngineHeartbeatRoute: typeof ApiPublicEngineHeartbeatRoute
  ApiPublicEngineIngestOpen_positionsRoute: typeof ApiPublicEngineIngestOpen_positionsRoute
  ApiPublicEngineIngestOrderRoute: typeof ApiPublicEngineIngestOrderRoute
  ApiPublicEngineIngestSignalRoute: typeof ApiPublicEngineIngestSignalRoute
  ApiPublicEngineIngestTradeRoute: typeof ApiPublicEngineIngestTradeRoute
  ApiPublicEngineSignalsPendingRoute: typeof ApiPublicEngineSignalsPendingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/engine': {
      id: '/app/engine'
      path: '/engine'
      fullPath: '/app/engine'
      preLoaderRoute: typeof AppEngineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configure': {
      id: '/app/configure'
      path: '/configure'
      fullPath: '/app/configure'
      preLoaderRoute: typeof AppConfigureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/engine/heartbeat': {
      id: '/api/public/engine/heartbeat'
      path: '/api/public/engine/heartbeat'
      fullPath: '/api/public/engine/heartbeat'
      preLoaderRoute: typeof ApiPublicEngineHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/eth-price': {
      id: '/api/public/engine/eth-price'
      path: '/api/public/engine/eth-price'
      fullPath: '/api/public/engine/eth-price'
      preLoaderRoute: typeof ApiPublicEngineEthPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/demo-tick': {
      id: '/api/public/engine/demo-tick'
      path: '/api/public/engine/demo-tick'
      fullPath: '/api/public/engine/demo-tick'
      preLoaderRoute: typeof ApiPublicEngineDemoTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/config': {
      id: '/api/public/engine/config'
      path: '/api/public/engine/config'
      fullPath: '/api/public/engine/config'
      preLoaderRoute: typeof ApiPublicEngineConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/signals/pending': {
      id: '/api/public/engine/signals/pending'
      path: '/api/public/engine/signals/pending'
      fullPath: '/api/public/engine/signals/pending'
      preLoaderRoute: typeof ApiPublicEngineSignalsPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/ingest/trade': {
      id: '/api/public/engine/ingest/trade'
      path: '/api/public/engine/ingest/trade'
      fullPath: '/api/public/engine/ingest/trade'
      preLoaderRoute: typeof ApiPublicEngineIngestTradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/ingest/signal': {
      id: '/api/public/engine/ingest/signal'
      path: '/api/public/engine/ingest/signal'
      fullPath: '/api/public/engine/ingest/signal'
      preLoaderRoute: typeof ApiPublicEngineIngestSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/ingest/order': {
      id: '/api/public/engine/ingest/order'
      path: '/api/public/engine/ingest/order'
      fullPath: '/api/public/engine/ingest/order'
      preLoaderRoute: typeof ApiPublicEngineIngestOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/engine/ingest/open_positions': {
      id: '/api/public/engine/ingest/open_positions'
      path: '/api/public/engine/ingest/open_positions'
      fullPath: '/api/public/engine/ingest/open_positions'
      preLoaderRoute: typeof ApiPublicEngineIngestOpen_positionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppConfigureRoute: typeof AppConfigureRoute
  AppConnectRoute: typeof AppConnectRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEngineRoute: typeof AppEngineRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppConfigureRoute: AppConfigureRoute,
  AppConnectRoute: AppConnectRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEngineRoute: AppEngineRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicEngineConfigRoute: ApiPublicEngineConfigRoute,
  ApiPublicEngineDemoTickRoute: ApiPublicEngineDemoTickRoute,
  ApiPublicEngineEthPriceRoute: ApiPublicEngineEthPriceRoute,
  ApiPublicEngineHeartbeatRoute: ApiPublicEngineHeartbeatRoute,
  ApiPublicEngineIngestOpen_positionsRoute:
    ApiPublicEngineIngestOpen_positionsRoute,
  ApiPublicEngineIngestOrderRoute: ApiPublicEngineIngestOrderRoute,
  ApiPublicEngineIngestSignalRoute: ApiPublicEngineIngestSignalRoute,
  ApiPublicEngineIngestTradeRoute: ApiPublicEngineIngestTradeRoute,
  ApiPublicEngineSignalsPendingRoute: ApiPublicEngineSignalsPendingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
